version: '3.7'

services:
  mongodb:
    image: mongo:latest
    container_name: news-api-mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: news-api
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
